### ISSUE TITLE
Can not install on staruml 2.1.2

### ISSUE THREAD

**Issue by Richard-L-G** [staruml/XMI#2]
I don't know why. When I click on the 'install' button on the extension manager dialog it took a long time and reponse with overrite or install error message box.

**Comment by zengsn** [comment]
me, too

**Comment by niklauslee** [comment]
We've tested on Windows 7 and Mac OS X, but it successfully installed. What is your OS? and what about other extensions (Java or C++)?

**Comment by Richard-L-G** [comment]
I'm on Windows 7 Enterprise 64bit. Other extensions are all worked well.

**Comment by niklauslee** [comment]
Please try to install manually according to http://docs.staruml.io/en/latest/managing-extensions.html
If it fails also, please dump errors in console. (Debugs > Show DevTools)

**Comment by Richard-L-G** [comment]
There're cplus, csharp, java, markdown, php and relationship-view in the directory. However, there's no xmi. Where can I get the extension manually?

**Comment by niklauslee** [comment]
You can download .zip at github. Here is a direct link: https://github.com/staruml/XMI/archive/master.zip
Extract this zip file on the extensions path.
