### ISSUE TITLE
Not able to import Sparx Enterprise Architect XMI 2.1 export

### ISSUE THREAD

**Issue by carlyledavis** [staruml/XMI#3]
Hey guys,

I have been trying to use this product and I am not able to export a Enterprise Architect 2.1 XMI model.  The tool does not give any warnings or errors but seems to complete with none of the entities on the model.  I tried doing this import with a UML Domain model.  Thanks.

**Comment by niklauslee** [comment]
Could you provide the exported XMI model? (support@staruml.io)
