### ISSUE TITLE
Exported XML does not escape ampersand or quotes

### ISSUE THREAD

**Issue by JamesCC** [staruml/XMI#6]
When exporting XMI, the resulting XMI (XML) file does not seem to escape symbols that are not accepted in pure XML.

As a result, if descriptions have ampersands, quotes, etc. these files cannot be read using many XML parsers.  For example I was unsuccessfully parsing an exported XMI file with this problem using ElementTree in python.

Looks like this could be fixed in the convertJsonToXML() function when writing, by escaping the necessary characters in this function.  I haven't worked out where yet for the read equivalent since the code is very different.

**Comment by niklauslee** [comment]
Now available in v0.9.2
